name: 25-02-25 - Events worklow
on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: [user1]
  workflow_dispatch:
  workflow_call:
  # schedule:
  #  - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: just an execution
        run: echo "Hello"
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [17,21]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: ${{ matrix.java-version }}
  
  
